"""Dữ liệu duy nhất cho bộ Ông Trùm Tư Bản."""

TILES = [
    (0,"Khởi nghiệp 4.0","GÓC","Đi qua +2V; đến đúng: +1 R&D",None),
    (1,"Nhà máy Dệt may","SẢN XUẤT","Giá 10V • phí 2V",10),
    (2,"Giá trị thặng dư","THẺ T2","Rút 1 thẻ Chủ đề 2",None),
    (3,"Công ty Phần mềm","CÔNG NGHỆ","Giá 8V • phí 2V",8),
    (4,"Thuế Nhà nước","ĐIỀU TIẾT","Trả 2V hoặc 3V: XH +3",None),
    (5,"KCN Bắc Ninh","KHU CN","Giá 8V • phí 2V",8),
    (6,"Ngân hàng thương mại","TÀI CHÍNH","Vay • gửi vốn • trả nợ",None),
    (7,"Quan hệ lao động","THẺ T2","Rút 1 thẻ Chủ đề 2",None),
    (8,"Khu dân cư công nhân","BẤT ĐỘNG SẢN","Giá 6V • phí 1V",6),
    (9,"Thị trường ASEAN","QUỐC TẾ","Giá 12V • phí 3V",12),
    (10,"Khủng hoảng kinh tế","GÓC","Rút thẻ; không giao dịch",None),
    (11,"Nhà máy Chế biến","SẢN XUẤT","Giá 12V • phí 2V",12),
    (12,"Công ty Tự động hóa","CÔNG NGHỆ","Giá 10V • phí 2V",10),
    (13,"Cạnh tranh thị trường","THẺ T4","Rút 1 thẻ Chủ đề 4",None),
    (14,"Khu đô thị mới","BẤT ĐỘNG SẢN","Giá 8V • phí 2V",8),
    (15,"Cảng Cát Lái","QUỐC TẾ","Giá 10V • phí 2V",10),
    (16,"Thương lượng tập thể","LAO ĐỘNG","Lương +1 bậc hoặc HL −10",None),
    (17,"KCN Đà Nẵng","KHU CN","Giá 10V • phí 2V",10),
    (18,"Trung tâm tài chính","TÀI CHÍNH","Giá 12V • phí 3V",12),
    (19,"Toàn cầu hóa","THẺ T6","HN +1; rút thẻ Chủ đề 6",None),
    (20,"Công đoàn đình công","GÓC","Kiểm tra đình công",None),
    (21,"Nhà máy Điện tử","SẢN XUẤT","Giá 14V • phí 3V",14),
    (22,"Cách mạng công nghiệp","CÔNG NGHỆ","Rút 2 CN, giữ 1",None),
    (23,"Công ty AI","CÔNG NGHỆ","Giá 12V • phí 3V",12),
    (24,"Giá trị thặng dư tương đối","THẺ T2","Rút 1 thẻ Chủ đề 2",None),
    (25,"Đất trung tâm đô thị","BẤT ĐỘNG SẢN","Giá 10V • phí 2V",10),
    (26,"Lợi tức ngân hàng","TÀI CHÍNH","Gửi 4V → nhận 5V/2 vòng",None),
    (27,"Cảng Hải Phòng","QUỐC TẾ","Giá 12V • phí 3V",12),
    (28,"Khu công nghệ cao","KHU CN","Giá 12V • phí 3V",12),
    (29,"Thị trường Đông Á","QUỐC TẾ","Giá 14V • phí 3V",14),
    (30,"Thanh tra chống độc quyền","GÓC","ĐQ: TT +2; khác: TT −1",None),
    (31,"Nhà máy Bán dẫn","SẢN XUẤT","Giá 16V • phí 4V",16),
    (32,"Tập đoàn Nền tảng số","CÔNG NGHỆ","Giá 14V • phí 4V",14),
    (33,"Biến động thế giới","THẺ T6","Rút 1 thẻ Chủ đề 6",None),
    (34,"Đặc khu bất động sản","BẤT ĐỘNG SẢN","Giá 12V • phí 3V",12),
    (35,"Độc quyền thị trường","ĐỘC QUYỀN","Kiểm tra 60% / chào mua CP",None),
    (36,"Sở giao dịch & Quỹ","TÀI CHÍNH","Giá 14V • phí 4V",14),
    (37,"Thị trường Toàn cầu","QUỐC TẾ","Giá 16V • phí 4V",16),
    (38,"Thuế lũy tiến","ĐIỀU TIẾT","10% tiền; min 2V, max 6V",None),
    (39,"Cảng trung chuyển QT","QUỐC TẾ","Giá 14V • phí 4V",14),
]

# Mỗi thẻ: mã, chủ đề, tiêu đề, tình huống, lựa chọn A/B/C, ghi chú học thuật.
EVENTS = [
('T2-01','T2','CA LÀM KÉO DÀI','Đơn hàng gấp, cần thêm 2 giờ làm.','A Phụ cấp: −2V; m +1; HL +5','B Giữ lương: m +3; HL −10; XH −5','C Tuyển ca: −3V; +1 LĐ; HL +5','Kéo dài ngày lao động làm tăng giá trị thặng dư tuyệt đối.'),
('T2-02','T2','DÂY CHUYỀN TỰ ĐỘNG','Đối thủ đưa máy mới vào sản xuất.','A Mua máy: −6V; +1 CN; −1 LĐ','B Đào tạo: −5V; +1 CN; HL +5','C Không đầu tư: nếu kém CN, π −2V','Máy chuyển giá trị; năng suất cao có thể làm tăng m tương đối.'),
('T2-03','T2','LƯƠNG TỐI THIỂU TĂNG','Mức lương tối thiểu tăng một bậc.','A Tuân thủ: −3V; HL +10; XH +5','B Đào tạo: −5V; +1 CN; HL +5','C Cắt 1 LĐ: +1V; HL −10; XH −10','Tiền công biểu hiện giá trị/giá cả sức lao động.'),
('T2-04','T2','KHAN HIẾM LAO ĐỘNG','Thiếu lao động lành nghề.','A Tăng lương: −3V; HL +10; m +1','B Đào tạo: −4V; +1 CN; HL +5','C Thuê ngoài: −2V; π +1V; HL −5','Tái sản xuất lao động phức tạp gồm chi phí đào tạo.'),
('T2-05','T2','GIÁ NGUYÊN LIỆU TĂNG','Đầu vào của ngành tăng giá.','A Mua: −4V; π −2V','B Tiết kiệm: −5V; +1 CN; c −1/lô','C Ngừng lô: π −3V; HL +5','Nguyên liệu thuộc c và chuyển giá trị vào sản phẩm.'),
('T2-06','T2','QUỸ LƯƠNG MINH BẠCH','Người lao động yêu cầu công khai thang lương.','A Công khai: −1V; HL +10; XH +10','B Thưởng sản phẩm: m +2; HL −5','C Trì hoãn: +1V; HL −10','Lương thời gian và lương sản phẩm là hai hình thức tiền công.'),
('T2-07','T2','ĐÌNH CÔNG ĐÒI LƯƠNG','Công đoàn yêu cầu chia sẻ thành quả.','A Thương lượng: −4V; HL +15; XH +10','B Từ chối: mất 2 SX; HL −15; XH −10','C Chia lợi nhuận: π −2V/2 vòng; HL +15','Xung đột phân phối v và m phản ánh quan hệ lợi ích.'),
('T2-08','T2','CẦU THỊ TRƯỜNG GIẢM','Hàng hóa khó tiêu thụ.','A Hạ giá: π −2V; giữ sản lượng','B Giảm 1 LĐ: +2V; HL −10; XH −5','C Tồn kho: −1V; bán 4V khi cầu tăng','m chỉ thành lợi nhuận thực hiện khi hàng hóa được bán.'),
('T2-09','T2','KHẤU HAO MÁY MÓC','Thiết bị đến kỳ đại tu.','A Quỹ thay thế: −3V; bảo toàn máy','B Trì hoãn: +2V; gieo 1–2 mất máy','C Thuê thiết bị: −2V; π −1V','Tư bản cố định chuyển từng phần giá trị qua khấu hao.'),
('T2-10','T2','TĂNG CƯỜNG ĐỘ','Có thể nâng định mức lao động.','A Có thưởng: m +2; −1V; HL −5','B Không thưởng: m +3; HL −10; XH −5','C Giữ định mức: HL +5','Cường độ cao làm lượng lao động hao phí tăng.'),
('T2-11','T2','TAI NẠN LAO ĐỘNG','Một sự cố xảy ra trong xưởng.','A An toàn: −4V; HL +10; XH +10','B Bồi thường ít: −2V; HL −10; XH −10','C Che giấu: gieo 1–3 phạt 8V; XH −15','Điều kiện lao động thuộc tái sản xuất sức lao động.'),
('T2-12','T2','BIẾN ĐỘNG NHÂN SỰ','Lao động có tay nghề muốn nghỉ.','A Tăng lương: −3V; HL +10','B Chấp nhận: −1 LĐ; m −1','C Tự động hóa: −6V; +1 CN; −1 LĐ','Tư bản khả biến mua sức lao động, nguồn tạo giá trị mới.'),
('T2-13','T2','HAI PHƯƠNG ÁN ĐẦU TƯ','Máy móc hay tuyển thêm người?','A Máy: −8V; +2 CN; π sau +3V','B Người: −4V; +2 LĐ; m +2','C Kết hợp: −6V; +1 CN; +1 LĐ; HL +5','p′ = m/(c+v); c tăng làm mẫu số tăng trước.'),
('T3-01','T3','PHÂN CHIA LỢI NHUẬN','Bạn quyết định dùng phần thặng dư.','A Tái đầu tư: −5V; +1 máy/CN','B Dự phòng: nhận token chống khủng hoảng','C Cổ tức: +3V; không nâng cấp lượt này','Tích lũy là tư bản hóa một phần giá trị thặng dư.'),
('T3-02','T3','VAY VỐN MỞ RỘNG','Ngân hàng đề nghị tài trợ.','A Vay 8V, trả 10V/3 vòng; +1 NM','B Vay 5V, trả 6V/2 vòng; +1 CN','C Không vay: không đổi','Lợi tức là phần lợi nhuận trả cho tư bản cho vay.'),
('T3-03','T3','LÃI SUẤT TĂNG','Chi phí tín dụng tăng đột ngột.','A Trả sớm: −6V; xóa 1 nợ','B Gia hạn: −2V; nợ đáo hạn +2V','C Bán tài sản: +5V; bỏ tài sản','Lãi suất biến động theo cung–cầu tư bản cho vay.'),
('T3-04','T3','ĐẤT GẦN METRO','Kỳ vọng hạ tầng đẩy giá đất.','A Mua: −7V; +1 BĐS; bong bóng +2','B Thuê: −3V; π +2V/2 vòng','C Không tham gia','Độc quyền sở hữu đất là cơ sở của địa tô.'),
('T3-05','T3','BONG BÓNG NHÀ ĐẤT','Giá đất tăng nóng.','A Bán: bỏ BĐS; +10V; bong bóng −2','B Giữ: gieo 1–3 giá còn 3V','C Mua: −6V; +1 BĐS; bong bóng +3','Đầu cơ dựa trên chênh lệch giá, không tạo giá trị mới.'),
('T3-06','T3','TƯ BẢN CHUYỂN NGÀNH','Công nghệ đang có p′ cao.','A Chuyển 5V: +1 CN; π sau +2V','B Giữ ngành: token giảm chi phí 2V','C Đa dạng: −3V; π +1V/3 vòng','Cạnh tranh liên ngành hướng tới lợi nhuận bình quân.'),
('T3-07','T3','THƯƠNG PHIẾU ĐẾN HẠN','Một khoản tín dụng thương mại đáo hạn.','A Trả 4V: uy tín +1','B Chiết khấu: +3V; nợ 4V vòng sau','C Vỡ hạn: uy tín −2; lãi sau +2V','Tín dụng rút ngắn lưu thông nhưng truyền rủi ro.'),
('T3-08','T3','NỢ XẤU LAN RỘNG','Cú sốc tín dụng lan qua hệ thống.','A Dùng Dự phòng: vô hiệu','B Bán CP: +5V; ĐQ −1','C Tái cơ cấu: −3V; cấm vay 2 vòng','Tín dụng thúc đẩy tập trung và khuếch đại khủng hoảng.'),
('T3-09','T3','THUẾ ĐẤT BỎ HOANG','Nhà nước đánh thuế đất không sử dụng.','A Đưa vào SX: −4V; BĐS → NM','B Nộp thuế: −3V','C Bán: +5V; bỏ BĐS','Chính sách đất tác động chiếm hữu địa tô và đầu cơ.'),
('T3-10','T3','ĐỊA TÔ CHÊNH LỆCH','Một khu đất có vị trí vượt trội.','A Hạ tầng: −5V; π +3V/2 vòng','B Cho thuê: +2V/vòng ×3','C Bán khai thác: +6V','Khác biệt vị trí có thể ổn định hóa lợi nhuận thành địa tô.'),
('T3-11','T3','TÍCH LŨY HAY PHÚC LỢI','Chọn cách phân phối quỹ năm nay.','A Tái đầu tư: −7V; +2 CN; HL −5','B Chia đều: −5V; +1 CN; HL +10','C Thưởng: −4V; HL +15; XH +10','Quy mô tích lũy tùy khối lượng m và tỷ lệ phân chia.'),
('T3-12','T3','THÂU TÓM NHÀ MÁY','Một nhà máy phá sản được rao bán.','A Mua: −7V; +1 NM; ĐQ +1','B Liên doanh: −4V; π +1V/4 vòng','C Nhường người yếu nhất mua 6V','Tập trung hợp nhất tư bản có sẵn; khác với tích tụ.'),
('T3-13','T3','LẠM PHÁT TÀI SẢN','Sức mua tiền giảm, giá tài sản tăng.','A Giữ tiền: −2V','B Mua máy: −6V; +1 CN','C Mua đất: −5V; +1 BĐS; bóng +2','Giá danh nghĩa tăng không đồng nghĩa giá trị thực tăng.'),
('T4-01','T4','CUỘC CHIẾN GIÁ','Đối thủ giảm giá để giành khách.','A Giảm sâu: π −3V; ĐQ +2 nếu có CN','B Giữ giá: ĐQ −1; +2V','C Chất lượng: −4V; +1 CN','Độc quyền không thủ tiêu cạnh tranh.'),
('T4-02','T4','SÁP NHẬP NGANG','Một đối thủ cùng ngành chào bán.','A Mua: −10V; +3 ĐQ; +1 NM','B CP thiểu số: −5V; +1 ĐQ','C Từ chối: XH +5','Tập trung sản xuất tạo cơ sở cho tổ chức độc quyền.'),
('T4-03','T4','ẤN ĐỊNH GIÁ','Một cartel mời bạn tham gia.','A Tham gia: π +4V/2 vòng; ĐQ +2; XH −10','B Từ chối: XH +10','C Tố giác: XH +5; ĐQ −1','Cartel thỏa thuận giá/sản lượng nhưng vẫn có mâu thuẫn.'),
('T4-04','T4','SÁNG CHẾ NỀN TẢNG','Một bằng sáng chế quan trọng được bán.','A Độc quyền: −7V; +1 CN; ĐQ +2','B Cấp phép mở: −3V; +1 CN; XH +10','C Bỏ qua','Sở hữu trí tuệ có thể tạo độc quyền tạm thời.'),
('T4-05','T4','NGÂN HÀNG VÀ HĐQT','Ngân hàng muốn ghế quản trị.','A Nhận 8V; ĐQ +1; trả 2V/3 vòng','B Phát hành CP: +6V; ĐQ −1','C Không huy động','Tư bản tài chính gắn tư bản ngân hàng với công nghiệp.'),
('T4-06','T4','THANH TRA ĐỘC QUYỀN','Cơ quan cạnh tranh mở điều tra.','A Phạt: −2V × ĐQ; ĐQ −2','B Mở hệ sinh thái: −3V; ĐQ −1; XH +10','C Kiện: −4V; gieo 1–3 phạt thêm 6V','Điều tiết vừa kiềm chế vừa đan xen quyền lực tập đoàn.'),
('T4-07','T4','HIỆU ỨNG MẠNG','Nền tảng càng đông càng có lợi.','A Trợ giá: −5V; ĐQ +2; XH −5','B Tăng phí: π +4V; ĐQ +1; XH −10','C Liên thông: π −1V; XH +10','Hiệu ứng mạng và dữ liệu tạo rào cản gia nhập.'),
('T4-08','T4','ĐỊNH GIÁ LOẠI TRỪ','Có thể bán dưới chi phí để ép đối thủ.','A Bán lỗ: −5V; sau +3 ĐQ; XH −15','B Năng suất: −4V; +1 CN; ĐQ +1','C Không theo: XH +5; ĐQ −1','Giá độc quyền phân phối lại giá trị, không tạo giá trị mới.'),
('T4-09','T4','HỢP ĐỒNG ĐỘC QUYỀN','Nhà cung cấp đề nghị khóa thị trường.','A Độc quyền: −3V; ĐQ +2; c −2','B Không độc quyền: −2V; c −1; XH +5','C Tự SX: −6V; +1 NM; ĐQ +1','Liên kết dọc có thể dựng rào cản cạnh tranh.'),
('T4-10','T4','DỮ LIỆU KHÁCH HÀNG','Kho dữ liệu có giá trị thương mại.','A Quảng cáo: +5V; ĐQ +2; XH −10','B Ẩn danh: +1V; XH +10; HN +1','C Bán: +7V; XH −15; rủi ro phạt','Dữ liệu tăng quyền lực thị trường, không tự tạo giá trị mới.'),
('T4-11','T4','TẬP ĐOÀN ĐA NGÀNH','Cơ hội lập holding xuất hiện.','A Holding: −8V; ĐQ +2; π tối đa +3V','B Chuyên môn: −4V; +2 CN','C Liên minh: −3V; ĐQ +1; HN +1','Holding kiểm soát nhiều doanh nghiệp qua cổ phần.'),
('T4-12','T4','ĐỐI THỦ NHỎ ĐỘT PHÁ','Một startup có công nghệ mới.','A Mua: −6V; +1 CN; ĐQ +2; XH −5','B Cải tiến: −4V; +1 CN; ĐQ +1','C Hợp tác: −3V; +1 CN; HN +1; XH +5','Độc quyền vẫn chịu sức ép đổi mới và người mới.'),
('T4-13','T4','LỢI NHUẬN ĐỘC QUYỀN','Nếu ĐQ ≥6, chọn cách dùng quyền lực.','A Tăng giá: π +5V; XH −15; TT +1','B Mở rộng: −3V; +1 NM; ĐQ +1','C Giảm giá: π +1V; XH +10; ĐQ −1','Lợi nhuận độc quyền cao là phần vượt bình quân.'),
('T6-01','T6','HIỆP ĐỊNH TỰ DO','Thuế quan giảm, thị trường mở rộng.','A Xuất khẩu: −2V; π +4V; HN +2','B Nội địa: π +1V','C Nâng chuẩn: −5V; +1 CN; HN +2','Hội nhập mở thị trường đồng thời tăng cạnh tranh.'),
('T6-02','T6','VỐN FDI','Nhà đầu tư nước ngoài đề nghị góp vốn.','A Nhận 8V; HN +2; trả 2V/3 vòng','B Liên doanh: +4V; +1 CN; HN +2','C Từ chối: ĐQ +1; HN −1','FDI là xuất khẩu tư bản có quyền quản lý.'),
('T6-03','T6','NHÀ MÁY NƯỚC NGOÀI','Có cơ hội đầu tư ra nước ngoài.','A FDI: −10V; HN +3; π +4V/vòng','B Cho vay: −6V; nhận 8V/3 vòng','C Cấp phép: +2V/3 vòng; HN +1','Xuất khẩu tư bản gồm trực tiếp và gián tiếp.'),
('T6-04','T6','CHIẾN TRANH THƯƠNG MẠI','Hai thị trường áp thuế trả đũa.','A Chuyển thị trường: −3V; HN +1','B Chịu thuế: π −4V/2 vòng','C Nội địa hóa: −6V; +1 CN; XH +5','Toàn cầu hóa không xóa cạnh tranh quốc gia.'),
('T6-05','T6','ĐỨT GÃY CHUỖI CUNG','Đầu vào quốc tế bị gián đoạn.','A Đa dạng: −4V; HN +1; miễn lần sau','B Dự trữ: −3V; +2 nguyên liệu','C Chờ: mất sản xuất lượt này','Chuỗi toàn cầu tăng chuyên môn hóa và phụ thuộc.'),
('T6-06','T6','QUY TẮC XUẤT XỨ','Hàng xuất khẩu phải đạt tỷ lệ nội địa.','A Nội địa hóa: −5V; +1 CN; XH +5; HN +1','B Nhập rẻ: π +2V; HN −1','C Chứng nhận: −2V; HN +1','Hội nhập đi cùng cam kết thể chế và tiêu chuẩn.'),
('T6-07','T6','CHUYỂN GIAO CÔNG NGHỆ','Đối tác chào một dây chuyền mới.','A Mua: −7V; +2 CN; HN +1','B Viện–DN: −5V; +1 CN; XH +5','C Gia công: π +3V/2 vòng; HN +1','Làm chủ công nghệ cần học hỏi và năng lực nội sinh.'),
('T6-08','T6','HẠ TẦNG CÔNG NGHIỆP','Cần góp vốn cho cảng và KCN.','A Logistics: −6V; HN +2; XK −2V','B KCN: −8V; +1 NM; HN +1','C Không đầu tư','Công nghiệp hóa là chuyển đổi kỹ thuật và năng suất.'),
('T6-09','T6','TỰ ĐỘNG HÓA NHANH','Nâng cấp sẽ thay đổi cơ cấu việc làm.','A Nhanh: −8V; +2 CN; −2 LĐ; HL −10','B Có đào tạo: −9V; +2 CN; XH +5','C Trì hoãn: HL +5; π sau −2V','Hiện đại hóa nâng năng suất nhưng dịch chuyển việc làm.'),
('T6-10','T6','TỶ GIÁ BIẾN ĐỘNG','Đồng nội tệ giảm giá mạnh.','A Xuất khẩu: π +3V; đầu vào −2V','B Phòng hộ: −2V; bỏ qua','C Nội địa: −4V; XH +5; c sau −1','Tỷ giá tác động trái chiều đến xuất và nhập.'),
('T6-11','T6','CHUẨN LAO ĐỘNG QT','Thị trường mới yêu cầu chuẩn lao động.','A Nâng chuẩn: −4V; HL +10; XH +10; HN +2','B Tối thiểu: −2V; HN +1','C Né: π +2V; XH −10; rủi ro cấm XK','Hội nhập gồm cả chuẩn lao động và quản trị.'),
('T6-12','T6','THUẾ CARBON BIÊN GIỚI','Hàng phát thải cao bị phụ phí.','A Sạch: −7V; +2 CN; HN +2; XH +10','B Trả phí: π −3V mỗi XK','C Rút: HN −2; π nội địa +1V','Tiêu chuẩn xanh tái định hình lợi thế cạnh tranh.'),
('T6-13','T6','KHỦNG HOẢNG TOÀN CẦU','Cú sốc lan qua tài chính và thương mại.','A Dự phòng: bỏ token; π −1V','B Thu hẹp: HN −2; bán tài sản +5V','C Giữ mạng: −5V; sau 2 vòng π +4V','Liên kết toàn cầu truyền cú sốc nhưng giúp đa dạng hóa.'),
]

TECHS = [
('Quản trị số','Mỗi vòng 1 lần: xem 2 thẻ sự kiện, chọn 1.'),
('Tiết kiệm năng lượng','Giảm c 1V cho lô sản xuất đầu tiên mỗi vòng.'),
('Thương mại điện tử','Khi cầu thấp, được tính như cầu bình thường 1 lần/vòng.'),
('Tự động hóa','Tăng công suất nhà máy +1; khi triển khai HL −5.'),
('AI dự báo','Sau khi tung xúc xắc, được đổi ±1 bước, 1 lần/vòng.'),
('Năng lượng xanh','Miễn một sự kiện năng lượng; XH +5 khi nhận.'),
('Robot công nghiệp','Doanh thu +1V/lô; cần c đầu tư 5V.'),
('Chuỗi khối logistics','Xuất khẩu giảm 1V logistics.'),
('Bằng sáng chế mở','Nhận 1V khi đối thủ triển khai cùng loại; XH +5.'),
('Sản xuất tinh gọn','Giảm c 1V/lô, không cộng dồn với tiết kiệm năng lượng.'),
('An toàn thông minh','Miễn tai nạn lao động kế tiếp; HL +5.'),
('Đào tạo số','Một LĐ được tính là lành nghề; giá trị mới +1V/lô.'),
]

